# =============================================================================
# Figure Generation: Individual Trajectories, 6-Step Predictions, Survival Probabilities
# =============================================================================
# Produces the main manuscript figure for individual-level prediction:
#   - Figure 3: Back-transformed individual biomarker trajectories and six-step-ahead
#     predictions in original clinical units, with Monte Carlo prediction intervals
#     for mortality (representative patient observed to month 35)
#   - An intermediate standardized-scale plot (diagnostic, not in manuscript)
#
#   Note: Figure 2 (population trends with 95% CI) is generated by albumin_fit.R.
#         Figure 1 (10 random patients + KM curve) is a raw-data plot, generated separately.
#
# Run order: 3 of 4
#   1. albumin_fit.R
#   2. bootstrap_ci.R
#   3. albumin_plot.R          <- YOU ARE HERE
#
# Inputs:
#   albumin_data_0509.RData              # data_split_in, z_in, X00_cube_in
#   filter_estimate_OU_withP.R           # Kalman filter function
#   theta_fit_theta_result_3.RData       # theta_result: bootstrap parameter list;
#                                        #   theta_result[[2]] = point estimate (natural scale)
#   theta_fit_fit_joint_albumin_8.RData  # fit_joint_albumin: optim object;
#                                        #   fit_joint_albumin$par = theta_trans_est (log scale)
#   restandardize_for_plot_0505.RData    # mean_alb, sd_alb, mean_idwg, sd_idwg, etc.
#                                        # for back-transforming to original clinical units
#
# Outputs:
#   0509_6pt_3156.png           # intermediate: individual trajectories on standardized scale
#                               # (not used in manuscript; diagnostic check)
#   0509_6pt_130_noCI_0904.pdf  # Figure 3 in manuscript: back-transformed individual
#                               # trajectories (subject i=130, observed to month 35) +
#                               # six-month-ahead mortality probability subplot
#
# Note: Figure 2 (population trends with 95% CI) is generated by albumin_fit.R, not here.
#       Figure 1 (10 random patients + KM curve) is a raw-data plot, generated separately.
#
# Monte Carlo survival probability (Option B, Section 4.3 of paper):
#   M = 120 samples drawn from the joint posterior of the state vector alpha = (alpha_u, alpha_v)
#   at each time point. Samples grouped into G = 20 groups of 6 and averaged (group_size = 6).
#   R = 20,000 random tuples of group indices combined across 6 steps to estimate
#   P(death within 6 months | data up to month t). Shaded region = 95% empirical CI.
# =============================================================================

rm(list = ls())

# --- USER: set this to the directory containing all data and script files ---
ROOT_DIR <- "."
setwd(ROOT_DIR)

rm(list = ls())
setwd(ROOT_DIR)
load("albumin_data_0509.RData")
rm(fit_joint_albumin_1)

set.seed(240)

source("filter_estimate_OU_withP.R")


library(data.table)
library(dplyr)
library(assist)
library(gridExtra) 
library("reshape2")
library("ggplot2")
library(survival)
library(survminer)
library(ggpubr)

# select m subjects
m = dim(data_split_in)[3]  #6000
idx = c(1:m)  #
data_split_in = data_split_in[,, idx]
z_in = z_in[idx,]
X00_cube_in = X00_cube_in[idx,,]
npt = dim(data_split_in)[2]
dummy_A = z_in
dummy_A[dummy_A == 1] = NA
A_list_in = list()
for (j in 1:npt){
  A_list_in[[j]] = (1:m)[!is.na(dummy_A[, j])]
}

dummy_AB = z_in
AB_list_in = list()
for (j in 1:npt){
  AB_list_in[[j]] = (1:m)[!is.na(dummy_AB[, j])]
}

died = apply(z_in, 1, sum, na.rm = TRUE)
table(died)

q = dim(data_split_in)[1]
p = dim(X00_cube_in)[2]
m = dim(data_split_in)[3]
npt = dim(data_split_in)[2]
tvec = 1:npt
nsteps = 6
#---------------------------------------------------------------------------------------------------------------------
load("theta_fit_theta_result_3.RData")
load("theta_fit_fit_joint_albumin_8.RData")
theta_est = theta_result[[2]]

theta_trans_est = fit_joint_albumin$par 
theta_trans_long_est = theta_trans_est[1:(0.5 * q^2 + 3.5 * q)]  #1:30, further includes 10 l's

filter_est = filter_estimate_OU_withP(theta_trans_long_est, data_split_in, A_list_in)
f_filter_est = filter_est$f_filter_mat
b_filter_est = filter_est$b_filter_cube
f_pred_est = filter_est$f_pred_mat
b_pred_est = filter_est$b_pred_cube
P0_est = filter_est$P0_cube  
P1_est = filter_est$P1_cube
P2_est = filter_est$P2_cube
P3_est = filter_est$P3_cube
P0_tt_est = filter_est$P0_tt_cube
P1_tt_est = filter_est$P1_tt_cube
P2_tt_est = filter_est$P2_tt_cube
P3_tt_est = filter_est$P3_tt_cube

Z00 = t(c(0, 0))
Z00[1, 1] = 1
Z_u = kronecker(diag(q), Z00)
Z_v = diag(q)

zeta_vec = theta_est[1:q]
nu2_vec = theta_est[(q+1):(2*q)]
xi_vec = theta_est[(2*q+1):(3*q)]

dt = 1.0
T00 = diag(2)
T00[1, 2] = dt
T_u = kronecker(diag(q), T00)
T_v = diag(exp(- xi_vec * dt))

Lambda = matrix(0, 2, 2)
Lambda[0, 0] = dt*dt*dt/3
Lambda[0, 1] = Lambda[1, 0] = dt*dt/2
Lambda[1, 1] = dt
Sig_u = kronecker(diag(zeta_vec), Lambda)
Sig_v = diag(0.5*nu2_vec * (1 - exp(-2*xi_vec*dt))/xi_vec )   #Should be * not %%!!!

d_vec = theta_est[(3*q+1):(4*q)]
D = diag(d_vec)

if (q > 1){
  l_vec = theta_est[(4*q+1):(0.5 * q * q + 3.5 * q)]
  L = diag(q)
  tmp = lower.tri(L, diag = F)
  L[tmp] = l_vec
}else{L = diag(1)}
Sigma = L%*%D%*%t(L)

#######################################################################################################################################
# an example of one subject's trajectory Prediction estimate: Random effect Prediction estimate
#######################################################################################################################################
#These are all who actually died
died = apply(z_in, 1, sum, na.rm = TRUE)
table(died)
die_id = which(died == 1)
censor_id = which(died == 0)
time_surv = c()
for(i in 1:length(censor_id)){
  time_surv[i] = length(na.omit(z_in[censor_id[i],]))
}
sort(time_surv)
censor_id[c(1:length(time_surv))[time_surv == sort(time_surv, decreasing = TRUE)[1]]]

i = 254
last = 44

i = 81
last = 38

i = 130
last = 35
tvec_extra = 1:(last)
#----------------------------------------------------------------------------------------------------------------------------------------------

#----------------------------------------------------------------------------------------------------------------------------------------------------------
# ALBUMIN plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, ALBUMIN = data_split_in[1,, i])
filter_data_extra_select = data.frame(time = tvec_extra, 
                                      ALBUMIN = c(f_filter_est[1,1:last] + b_filter_est[1, i, 1:last]))
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_ALBUMIN_2 = ggplot(obs_data[1:last, ], aes(x = time, y = ALBUMIN)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") +
  geom_point(aes(x = time, y = ALBUMIN, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        plot.title = element_text(size = 20),
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("ALB (g/dL)") +
  xlab("Months on dialysis treatment") 
# ggtitle("Prediction estimate of ALBUMIN for one individual")
p_ALBUMIN_2

#----------------------------------------------------------------------------------------------------------------------------------------------------------
# IDWG plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, IDWG = data_split_in[2,, i])

filter_data_extra_select = data.frame(time = tvec_extra, 
                                      IDWG = c(f_filter_est[2,1:last] + b_filter_est[2, i,1:last]))
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_IDWG_2 = ggplot(obs_data[1:last, ], aes(x = time, y = IDWG)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") + 
  geom_point(aes(x = time, y = IDWG, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("IDWG (%)") +
  xlab("Months on dialysis treatment") 
# ggtitle("Prediction estimate of IDWG for one individual")
p_IDWG_2

#----------------------------------------------------------------------------------------------------------------------------------------------------------
# SBP plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, SBP = data_split_in[3,, i])

filter_data_extra_select = data.frame(time = tvec_extra, 
                                      SBP= c(f_filter_est[3,1:last] + b_filter_est[3, i,1:last]))
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_SBP_2 = ggplot(obs_data[1:last, ], aes(x = time, y = SBP)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") + 
  geom_point(aes(x = time, y = SBP, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("SBP (mmHg)") +
  xlab("Months on dialysis treatment") 
p_SBP_2

#----------------------------------------------------------------------------------------------------------------------------------------------------------
# NLR plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, NLR = data_split_in[4,, i])

filter_data_extra_select = data.frame(time = tvec_extra, 
                                      NLR = c(f_pred_est[4,1:last] + b_pred_est[4, i,1:last]))
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_NLR_2 = ggplot(obs_data[1:last, ], aes(x = time, y = NLR)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") +
  geom_point(aes(x = time, y = NLR, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("NLR, square root") +
  xlab("Months on dialysis treatment") 
# ggtitle("Prediction estimate of NLR for one individual")
p_NLR_2

#----------------------------------------------------------------------------------------------------------------------------------------------------------
# Hemoglobin plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, HGB = data_split_in[5,, i])

filter_data_extra_select = data.frame(time = tvec_extra, 
                                      HGB = c(f_pred_est[5,1:last] + b_pred_est[5, i,1:last]))
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_HGB_2 = ggplot(obs_data[1:last, ], aes(x = time, y = HGB)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") +
  geom_point(aes(x = time, y = HGB, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("HGB (g/dL)") +
  xlab("Months on dialysis treatment") 
p_HGB_2

#----------------------------------------------------------------------------------------------------------------------------------------------------------
# dev.tool for filtering and predictions

# dev.new() 
png("0509_6pt_3156.png", width = 1000, height = 900)
ggarrange(p_ALBUMIN_2, p_IDWG_2, p_SBP_2, p_NLR_2, p_HGB_2, nrow = 3, ncol = 2)
dev.off()







load("restandardize_for_plot_0505.RData")
#----------------------------------------------------------------------------------------------------------------------------------------------------------
# ALBUMIN plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, ALBUMIN = data_split_in[1,, i]*sd_alb + mean_alb)
filter_data_extra_select = data.frame(time = tvec_extra, 
                                      ALBUMIN = c(f_filter_est[1,1:last] + b_filter_est[1, i, 1:last])*sd_alb + mean_alb)
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_ALBUMIN_2 = ggplot(obs_data[1:last, ], aes(x = time, y = ALBUMIN)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") +
  geom_point(aes(x = time, y = ALBUMIN, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        plot.title = element_text(size = 20),
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("ALB (g/dL)") +
  xlab("Months on dialysis treatment") +
  ylim(-3*sd_alb + mean_alb, 1*sd_alb + mean_alb) + 
  scale_x_continuous(breaks = c(0, 10, 20, 30, 38))
p_ALBUMIN_2


#----------------------------------------------------------------------------------------------------------------------------------------------------------
# IDWG plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, IDWG = data_split_in[2,, i]*sd_idwg + mean_idwg)

filter_data_extra_select = data.frame(time = tvec_extra, 
                                      IDWG = c(f_filter_est[2,1:last] + b_filter_est[2, i,1:last])*sd_idwg + mean_idwg)
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_IDWG_2 = ggplot(obs_data[1:last, ], aes(x = time, y = IDWG)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") + 
  geom_point(aes(x = time, y = IDWG, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("IDWG (%)") +
  xlab("Months on dialysis treatment") + 
  ylim(-2.4*sd_idwg + mean_idwg, 3*sd_idwg + mean_idwg) + 
  scale_x_continuous(breaks = c(0, 10, 20, 30, 38))
p_IDWG_2

#----------------------------------------------------------------------------------------------------------------------------------------------------------
# SBP plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, SBP = data_split_in[3,, i]*sd_sbp + mean_sbp)

filter_data_extra_select = data.frame(time = tvec_extra, 
                                      SBP= c(f_filter_est[3,1:last] + b_filter_est[3, i,1:last])*sd_sbp + mean_sbp)
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_SBP_2 = ggplot(obs_data[1:last, ], aes(x = time, y = SBP)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") + 
  geom_point(aes(x = time, y = SBP, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("SBP (mmHg)") +
  xlab("Months on dialysis treatment") + 
  ylim(-2.5*sd_sbp + mean_sbp, 1.3*sd_sbp + mean_sbp) + 
  scale_x_continuous(breaks = c(0, 10, 20, 30, 38))
p_SBP_2
#----------------------------------------------------------------------------------------------------------------------------------------------------------
# NLR plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, NLR = data_split_in[4,, i]*sd_nlr + mean_nlr)

filter_data_extra_select = data.frame(time = tvec_extra, 
                                      NLR = c(f_pred_est[4,1:last] + b_pred_est[4, i,1:last])*sd_nlr + mean_nlr)
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_NLR_2 = ggplot(obs_data[1:last, ], aes(x = time, y = NLR)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") +
  geom_point(aes(x = time, y = NLR, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("NLR, square root") +
  xlab("Months on dialysis treatment") 
p_NLR_2

#----------------------------------------------------------------------------------------------------------------------------------------------------------
# Hemoglobin plot
#----------------------------------------------------------------------------------------------------------------------------------------------------------
obs_data = data.frame(time = tvec, HGB = data_split_in[5,, i]*sd_hgb + mean_hgb)

filter_data_extra_select = data.frame(time = tvec_extra, 
                                      HGB = c(f_pred_est[5,1:last] + b_pred_est[5, i,1:last])*sd_hgb + mean_hgb)
filter_data_extra_select = cbind(filter_data_extra_select, rep(NA, last))
colnames(filter_data_extra_select)[ncol(filter_data_extra_select)] = c("status")
filter_data_extra_select$status[last] = "Died"

p_HGB_2 = ggplot(obs_data[1:last, ], aes(x = time, y = HGB)) +
  geom_line(data = filter_data_extra_select, color = "turquoise3") +
  geom_point(color = "turquoise3") +
  geom_point(aes(x = time, y = HGB, shape = status, size = 9),
             data = filter_data_extra_select) +
  scale_shape_manual(values=c(4))+
  theme_bw() +
  theme(legend.position="none", 
        axis.text=element_text(size = 20), 
        axis.title=element_text(size = 20)) + 
  ylab("HGB (g/dL)") +
  xlab("Months on dialysis treatment") + 
  ylim(-3*sd_hgb + mean_hgb, 2*sd_hgb + mean_hgb) + 
  scale_x_continuous(breaks = c(0, 10, 20, 30, 38))
p_HGB_2











library(data.table)
library(dplyr)
library(assist)
library(gridExtra)
library("reshape2")
library("ggplot2")
library(survival)
library(survminer)
library("abind")
library(MASS)

source("filter_estimate_OU_withP.R")

# select m subjects
q = dim(data_split_in)[1]
p = dim(X00_cube_in)[2]
m = dim(data_split_in)[3]  #5707
idx = c(1:m)  #???maybe set to 1000???
data_split_in = data_split_in[,, idx]
z_in = z_in[idx,]
X00_cube_in = X00_cube_in[idx,,]
npt = dim(data_split_in)[2]
dummy_A = z_in
dummy_A[dummy_A == 1] = NA
A_list_in = list()
for (j in 1:npt){
  A_list_in[[j]] = (1:m)[!is.na(dummy_A[, j])]
}

dummy_AB = z_in
AB_list_in = list()
for (j in 1:npt){
  AB_list_in[[j]] = (1:m)[!is.na(dummy_AB[, j])]
}

died = apply(z_in, 1, sum, na.rm = TRUE)
table(died)

q = dim(data_split_in)[1]
p = dim(X00_cube_in)[2]
m = dim(data_split_in)[3]
npt = dim(data_split_in)[2]
tvec = 1:npt
nsteps = 6
#---------------------------------------------------------------------------------------------------------------------
# filter_est_OU takes in log transformed theta_trans, llh_x_OU produces fit_joint_albumin$par which is log transformed
# theta_est is correct scale, used for defining parameters and logistic regression
theta_trans_est = fit_joint_albumin$par
theta_est = theta_trans_est
theta_est[1:(4 * q)] = exp(theta_trans_est[1:(4 * q)])
theta_trans_long_est = theta_trans_est[1:(0.5 * q^2 + 3.5 * q)]  #1:30, further includes 10 l's

filter_est = filter_estimate_OU_withP(theta_trans_long_est, data_split_in, A_list_in)
f_filter_est = filter_est$f_filter_mat
b_filter_est = filter_est$b_filter_cube
a_u_mat = filter_est$a_u_mat
a_v_cube = filter_est$a_v_cube
a_u_tt_mat = filter_est$a_u_tt_mat
a_v_tt_cube = filter_est$a_v_tt_cube
f_pred_est = filter_est$f_pred_mat
b_pred_est = filter_est$b_pred_cube
P0_est = filter_est$P0_cube
P1_est = filter_est$P1_cube
P2_est = filter_est$P2_cube
P3_est = filter_est$P3_cube
P0_tt_est = filter_est$P0_tt_cube
P1_tt_est = filter_est$P1_tt_cube
P2_tt_est = filter_est$P2_tt_cube
P3_tt_est = filter_est$P3_tt_cube

Z00 = t(c(0, 0))
Z00[1, 1] = 1
Z_u = kronecker(diag(q), Z00)
Z_v = diag(q)

zeta_vec = theta_est[1:q]
nu2_vec = theta_est[(q+1):(2*q)]
xi_vec = theta_est[(2*q+1):(3*q)]

dt = 1.0
T00 = diag(2)
T00[1, 2] = dt
T_u = kronecker(diag(q), T00)
T_v = diag(exp(- xi_vec * dt))

Lambda = matrix(0, 2, 2)
Lambda[0, 0] = dt*dt*dt/3
Lambda[0, 1] = Lambda[1, 0] = dt*dt/2
Lambda[1, 1] = dt
Sig_u = kronecker(diag(zeta_vec), Lambda)
Sig_v = diag(0.5*nu2_vec * (1 - exp(-2*xi_vec*dt))/xi_vec )

d_vec = theta_est[(3*q+1):(4*q)]
D = diag(d_vec)

if(q > 1){
  l_vec = theta_est[(4*q+1):(0.5 * q * q + 3.5 * q)]
  L = diag(q)
  tmp = lower.tri(L, diag = F)
  L[tmp] = l_vec
}else{L = diag(1)}
Sigma = L%*%D%*%t(L)

# gamma terms for logistic
gamm_vec = theta_est[(0.5 * q^2 + 3.5 * q + 1):(0.5 * q^2 + 4.5 * q)]
gamm_x   = theta_est[(0.5 * q^2 + 4.5 * q + 1):(0.5 * q^2 + 4.5 * q + p + 1)]

#######################################################################################################################################
# Build 6-step-ahead state means/covs for the chosen subject (needed for Option B)
#######################################################################################################################################
# choose subject/time
i = 130
last = 35
nsteps = 6
tvec_extra = 1:(last+nsteps)

# state means
a_u_mat_extra = matrix(0, nrow = 2*q, ncol = nsteps)
a_u_mat_extra[,1] = T_u %*% a_u_tt_mat[, last]
for(s in 2:nsteps) a_u_mat_extra[,s] = T_u %*% a_u_mat_extra[,s-1]

a_v_cube_extra = array(0, c(q, m, nsteps))
a_v_cube_extra[,,1] = T_v %*% a_v_tt_cube[,, last]
for(s in 2:nsteps) a_v_cube_extra[,,s] = T_v %*% a_v_cube_extra[,,s-1]

# state covariances
P0_est_extra = array(0, c(2*q, 2*q, nsteps))
P1_est_extra = array(0, c(2*q,   q, nsteps))
P2_est_extra = array(0, c(  q,   q, nsteps))
P3_est_extra = array(0, c(  q,   q, nsteps))

P0_est_extra[,,1] = T_u %*% P0_tt_est[,,last] %*% t(T_u) + Sig_u
P1_est_extra[,,1] = T_u %*% P1_tt_est[,,last] %*% t(T_v)
P2_est_extra[,,1] = T_v %*% P2_tt_est[,,last] %*% t(T_v) + Sig_v
P3_est_extra[,,1] = T_v %*% P3_tt_est[,,last] %*% t(T_v)
for(s in 2:nsteps){
  P0_est_extra[,,s] = T_u %*% P0_est_extra[,,s-1] %*% t(T_u) + Sig_u
  P1_est_extra[,,s] = T_u %*% P1_est_extra[,,s-1] %*% t(T_v)
  P2_est_extra[,,s] = T_v %*% P2_est_extra[,,s-1] %*% t(T_v) + Sig_v
  P3_est_extra[,,s] = T_v %*% P3_est_extra[,,s-1] %*% t(T_v)
}

#######################################################################################################################################
# === OPTION B: Grouped-combination Monte Carlo for survival subplot (p_survival) ===
#######################################################################################################################################
safe_chol <- function(S) {
  out <- try(chol(S), silent = TRUE)
  if (inherits(out, "try-error")) chol(S + diag(1e-8, nrow(S))) else out
}

build_store <- function(step, last,
                        a_u_mat, a_v_cube, P0_est, P1_est, P2_est, P3_est,
                        a_u_mat_extra, a_v_cube_extra, P0_est_extra, P1_est_extra, P2_est_extra, P3_est_extra,
                        subj_index) {
  a_store <- matrix(0, 2*q + q, last)
  P_store <- array(0, c(2*q + q, 2*q + q, last))
  if (step <= last - 1) {
    for (j in (1 + step):last) {
      a_store[, j - step] <- c(a_u_mat[, j], a_v_cube[, subj_index, j])
      P_store[, , j - step] <- rbind(
        cbind(P0_est[, , j], P1_est[, , j]),
        cbind(t(P1_est[, , j]), P2_est[, , j] + P3_est[, , j])
      )
    }
  }
  if (step > 0) {
    for (j in step:1) {
      idx_dst <- last - j + 1
      idx_src <- step - j + 1
      a_store[, idx_dst] <- c(a_u_mat_extra[, idx_src], a_v_cube_extra[, subj_index, idx_src])
      P_store[, , idx_dst] <- rbind(
        cbind(P0_est_extra[, , idx_src], P1_est_extra[, , idx_src]),
        cbind(t(P1_est_extra[, , idx_src]), P2_est_extra[, , idx_src] + P3_est_extra[, , idx_src])
      )
    }
  }
  list(a_store = a_store, P_store = P_store)
}

# stores for s = 0..5 steps ahead
stores <- lapply(0:(nsteps-1), function(s)
  build_store(step = s, last,
              a_u_mat, a_v_cube, P0_est, P1_est, P2_est, P3_est,
              a_u_mat_extra, a_v_cube_extra, P0_est_extra, P1_est_extra, P2_est_extra, P3_est_extra,
              subj_index = i))

set.seed(20250820)
M <- 120
G <- 20
group_size <- M %/% G
stopifnot(G * group_size == M)

compute_p_step_independent <- function(a_store, P_store, step_index, last, subj_index) {
  chol_list <- lapply(seq_len(last), function(j) safe_chol(P_store[, , j]))
  p_s <- matrix(NA_real_, nrow = M, ncol = last)
  for (k in 1:M) {
    for (j in 1:last) {
      z_kj <- rnorm(n = nrow(a_store))
      alpha_jk <- a_store[, j] + chol_list[[j]] %*% z_kj
      alpha_u <- alpha_jk[1:(2*q)]
      alpha_v <- alpha_jk[(2*q + 1):(2*q + q)]
      state_prev <- Z_u %*% alpha_u + Z_v %*% alpha_v
      jX <- min(j + (step_index - 1), last)
      X_prev <- c(1, X00_cube_in[i, , jX])
      logit_j <- as.numeric( crossprod(state_prev, gamm_vec) + crossprod(X_prev[-1], gamm_x[-1]) + gamm_x[1] )
      p_s[k, j] <- plogis(logit_j)
    }
  }
  p_s
}

# per-step M draws
p_by_step <- vector("list", nsteps)
for (s in 1:nsteps) {
  a_store_s <- stores[[s]]$a_store
  P_store_s <- stores[[s]]$P_store
  p_by_step[[s]] <- compute_p_step_independent(a_store_s, P_store_s, step_index = s, last = last, subj_index = i)
}

# group within-step into 20 groups of size 6 and average
group_id <- rep(1:G, each = group_size)
pbar_by_step <- vector("list", nsteps)
for (s in 1:nsteps) {
  p_s <- p_by_step[[s]]
  pbar_s <- matrix(NA_real_, nrow = G, ncol = last)
  for (g in 1:G) {
    idx_g <- which(group_id == g)
    pbar_s[g, ] <- colMeans(p_s[idx_g, , drop = FALSE])
  }
  pbar_by_step[[s]] <- pbar_s
}

# sample tuples of group indices across steps and combine
R <- 20000
set.seed(20250821)
tuple_mat <- matrix(sample.int(G, size = R * nsteps, replace = TRUE), nrow = R, ncol = nsteps)

p_path_R_by_time <- matrix(NA_real_, nrow = R, ncol = last)
for (j in 1:last) {
  surv_prod <- rep(1, R)
  for (s in 1:nsteps) {
    pbar_s_col <- pbar_by_step[[s]][ , j]
    ps_pick <- pbar_s_col[ tuple_mat[, s] ]
    surv_prod <- surv_prod * (1 - ps_pick)
  }
  p_path_R_by_time[, j] <- 1 - surv_prod
}

# summarize (mean and 95% empirical quantiles)
p_mean <- apply(p_path_R_by_time, 2, mean)
p_lwr  <- apply(p_path_R_by_time, 2, quantile, probs = 0.025)
p_upr  <- apply(p_path_R_by_time, 2, quantile, probs = 0.975)

p_hat <- data.frame(
  time      = seq_len(last),
  mort_prob = p_mean,
  lower     = p_lwr,
  upper     = p_upr
)

# survival subplot (Option B)
p_survival = ggplot(p_hat, aes(x = time, y = mort_prob)) +
  geom_ribbon(data = p_hat, fill = "cornsilk2", aes(ymin = lower, ymax = upper)) +
  geom_point(color = "coral3") +
  theme_bw() +
  theme(plot.title = element_text(size = 19),
        axis.text   = element_text(size=20), 
        axis.title  = element_text(size=20)) + 
  geom_line(data = p_hat, color = "coral") +
  ylab("Probability of mortality") +
  xlab("Months on dialysis treatment") +  
  # ggtitle("Semi-annual estimate for mortality, one individual") + 
  scale_x_continuous(breaks = c(0, 10, 20, 30, 38))

# ---- END OPTION B ----

pdf(file = "0509_6pt_130_noCI_0904.pdf", width = 15, height = 12, family = "Helvetica") # defaults to 7 x 7 inches
ggarrange(p_ALBUMIN_2, p_IDWG_2, p_SBP_2, p_NLR_2, p_HGB_2, p_survival, nrow = 3, ncol = 2)
dev.off()



## ---------------------------------------------------------------------------
## Create the final characteristics table
## ---------------------------------------------------------------------------
## ---- Helpers (use yours if already defined) -------------------------------
# install.packages(c("knitr","kableExtra"))  # if needed
library(dplyr)
library(knitr)
library(kableExtra)

##---------------------- helpers ----------------------##
mean_sd_fmt <- function(x, digits = c(1,1), na.rm = TRUE) {
  m <- mean(x, na.rm = na.rm)
  s <- sd(x, na.rm = na.rm)
  sprintf(paste0("%.", digits[1], "f (%.", digits[2], "f)"), m, s)
}
range_fmt <- function(x, digits = 0, na.rm = TRUE) {
  r <- range(x, na.rm = na.rm)
  fmt <- paste0("%.", digits, "f")
  paste0(sprintf(fmt, r[1]), " – ", sprintf(fmt, r[2]))
}
npct_fmt <- function(vec, level, digits = 0) {
  n <- sum(vec == level, na.rm = TRUE)
  d <- sum(!is.na(vec))
  p <- 100 * n / d
  sprintf(paste0("%d (%.", digits, "f%%)"), n, p)
}

##---------------------- data prep ----------------------##
# base = one row per patient at baseline (or your chosen reference month)
# If you only have the longitudinal file, create a baseline snapshot:
# base <- albumin_data_9 %>% group_by(dummyPATIENT_ID) %>% slice_min(time_on_trt, with_ties = FALSE) %>% ungroup()

# Build a single categorical Access variable if you don’t already have it:
base <- base %>%
  mutate(
    ACCESS_cat = dplyr::case_when(
      ACCESS_AVF_avg == 1 ~ "AVF",
      ACCESS_AVG_avg == 1 ~ "AVG",
      TRUE                 ~ "CVC"
    ),
    male = as.integer(male),            # ensure 0/1
    diabetic = as.integer(diabetic)
  )

END_MONTH <- max(albumin_data_9$time_on_trt, na.rm = TRUE)

##---------------------- rows ----------------------##
N <- nrow(base)
# title_line <- sprintf("Overall (N=%d)", N)

# Continuous sections: bold header + indented sublines
block_cont <- function(label, x, mean_digits = c(1,1), range_digits = 0) {
  rbind(
    c(paste0(label), ""),
    c("&nbsp;&nbsp;Mean (SD)", mean_sd_fmt(x, mean_digits)),
    c("&nbsp;&nbsp;Range",     range_fmt(x, range_digits))
  )
}

rows_cont <- rbind(
  block_cont("Age, years",           base$age,              c(1,1), 0),
  block_cont("EKTV",                 base$EKTV_avg,         c(2,2), 2),
  block_cont("Albumin (g/dL)",       base$ALBUMIN_avg,      c(2,2), 1),
  block_cont("IDWG %",                base$idwg_percent_avg, c(2,2), 2),
  block_cont("Pre-dialysis SBP (mmHg)",     base$PRE_SBP_avg,      c(1,1), 0),
  block_cont("NLR square root",                 base$nlr_avg_sqrt,     c(2,2), 2),
  block_cont("HGB (g/dL)",           base$hgb_avg,          c(2,2), 2)
)

# Categorical sections: bold header + level rows
block_cat <- function(label, vec, levels_show) {
  out <- matrix(ncol = 2, byrow = TRUE)
  out <- rbind(out, c(paste0(label), ""))
  for (lv in levels_show) {
    out <- rbind(out, c(paste0("&nbsp;&nbsp;", lv),
                        npct_fmt(vec, lv, digits = 0)))
  }
  out[-1, , drop = FALSE]  # remove first empty row created by seed
}

rows_cat <- rbind(
  block_cat("Female Sex", ifelse(base$male==1,"Male","Female"), c("Female")),
  block_cat("APOE ε4 carrier", rep(NA, N), character(0)),     # example stub if not present
  block_cat("Diabetic", ifelse(base$diabetic==1,"Yes","No"), c("Yes")),
  # Vascular access
  {
    lv <- c("AVF","AVG","CVC")
    r <- rbind(c("Vascular access",""))
    for (lvv in lv) {
      r <- rbind(r, c(paste0("&nbsp;&nbsp;", lvv),
                      npct_fmt(base$ACCESS_cat, lvv, digits = 0)))
    }
    r
  }
)

# Requested tail rows
rows_tail <- rbind(
  c("**Status at end of follow-up**",""),
  c(paste0("&nbsp;&nbsp;Alive at end (month ", END_MONTH, ")"),
    npct_fmt(base$alive_at_end, TRUE, digits = 0)),
  c(paste0("&nbsp;&nbsp;Censored before end (month ", END_MONTH, ")"),
    npct_fmt(base$censored_at_end, TRUE, digits = 0))
)

# Glue all together
tbl_mat <- rbind(rows_cont, rows_cat, rows_tail)
# colnames(tbl_mat) <- c("Characteristic", title_line)
tbl_df <- as.data.frame(tbl_mat, stringsAsFactors = FALSE)

##---------------------- render like the screenshot ----------------------##
note <- paste0(
  "Note. Continuous variables shown as mean (SD) and range. ",
  "Categorical variables shown as n (%). ")
# ,
#   "√NLR = square-root transformed neutrophil-to-lymphocyte ratio. ",
#   "AVF = arteriovenous fistula; AVG = arteriovenous graft; CVC = central venous catheter."
# )

kbl(tbl_df,
    booktabs = TRUE,
    align = c("l","r"),
    escape = FALSE,
    col.names = NULL,                     # <— hides the V1/V2 header row
    caption = "Table 1. Participant characteristics at the reference visit (Overall), unless otherwise specified."
) |>
  kable_styling(full_width = FALSE, position = "left",
                latex_options = c("hold_position")) |>
  row_spec(which(grepl("^\\*\\*", tbl_df$Characteristic)), bold = TRUE) |>
  column_spec(1, width = "10cm") |>
  add_header_above(setNames(c(1, 1), c(" ", title_line))) |>
  footnote(general = note,
           general_title = "",
           threeparttable = TRUE,
           fixed_small_size = TRUE)



