# =============================================================================
# Sensitivity Analysis: Three-Model Comparison on Synthetic Data
# =============================================================================
# Fits three joint model specifications on synthetic training data generated
# from the fitted cubic-OU model, and evaluates predictive performance on a
# held-out synthetic test set. This serves as a sensitivity analysis justifying
# the choice of OU process for individual trajectories (Section 5 of paper).
#
# Three model specifications compared:
#   1. Cubic-OU:    cubic spline population + OU individual process  (our model)
#   2. Cubic-Cubic: cubic spline population + cubic spline individual
#   3. Cubic-Local: cubic spline population + local level individual
#
# Run order: standalone (does not depend on albumin_fit.R pipeline)
#   Prerequisite: synth_data_train_cubic_OU.RData and synth_data_test_cubic_OU.RData
#                 must exist (generated by synth_gen_cubic_OU_fittedJM.R)
#
# Inputs:
#   synth_data_train_cubic_OU.RData  # synthetic training data (m=5707 subjects)
#   synth_data_test_cubic_OU.RData   # synthetic test data (m=5707 subjects)
#   theta_trans_3_0504.RData         # initial parameter values, final restart
#   theta_trans_3_0503.RData         # initial parameter values, 2nd restart (blending)
#   theta_trans_3_0502.RData         # initial parameter values, 1st restart (blending)
#   theta_trans_1_0404.RData         # initial survival subvector
#   data_preparation_functions.R     # standardization and array construction helpers
#   llh_survival_x_OU.R             # joint likelihood: cubic-OU
#   filter_estimate_OU_withP.R       # Kalman filter for OU model
#   llh_cs_cs.R                      # longitudinal likelihood: cubic-cubic
#   llh_cs_local.R                   # longitudinal likelihood: cubic-local
#   llh_joint_all_models.R           # joint likelihood: cubic-cubic and cubic-local
#   helper_functions_losses.R        # compute_risk_scores_from_filter, loss computation helpers
#
# Outputs:
#   fit_ou_synth.RData               # fitted cubic-OU parameters
#   fit_cc_synth.RData               # fitted cubic-cubic parameters
#   fit_cl_synth.RData               # fitted cubic-local parameters
#   model_comparison_results.RData   # all loss metrics (llh, MSE, AUC, C-index)
#   master_comparison_synth.RData    # full workspace snapshot (save.image at end)
#   model_comparison_plots.pdf       # comparison plots
#
# Parameter vector structure: see albumin_fit.R header.
# For cubic-cubic: d_v = 2q (individual cubic spline state dimension).
# For cubic-local: d_v = q  (individual local level state dimension).
# =============================================================================

rm(list = ls())

# --- USER: set this to the directory containing all data and script files ---
ROOT_DIR <- "."
setwd(ROOT_DIR)

library(data.table)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(survival)
library(pROC)

# =============================================================================
# 1. LOAD SYNTHETIC DATA
# =============================================================================

cat("Loading synthetic training and test data...\n")
load("synth_data_train_cubic_OU.RData")  # albumin_data_9_synth_train
load("synth_data_test_cubic_OU.RData")   # albumin_data_9_synth_test

source("data_preparation_functions.R")   # prepare_data_array, standardize_data_array, etc.

## Training data
cat("Preparing training data arrays...\n")
data_split_train_raw <- prepare_data_array(albumin_data_9_synth_train)
z_train              <- prepare_z_matrix(albumin_data_9_synth_train)
X00_cube_train_raw   <- prepare_X_cube(albumin_data_9_synth_train)

## Test data
cat("Preparing test data arrays...\n")
data_split_test_raw <- prepare_data_array(albumin_data_9_synth_test)
z_test              <- prepare_z_matrix(albumin_data_9_synth_test)
X00_cube_test_raw   <- prepare_X_cube(albumin_data_9_synth_test)

## Standardize using training data statistics (matching albumin_fit.R)
cat("Standardizing biomarkers and covariates...\n")
std_result       <- standardize_data_array(data_split_train_raw)
data_split_train <- std_result$data_standardized
bio_means        <- std_result$means
bio_sds          <- std_result$sds

q <- dim(data_split_train)[1]   # 5 biomarkers
data_split_test <- data_split_test_raw
for(k in 1:q){
  data_split_test[k,,] <- (data_split_test_raw[k,,] - bio_means[k]) / bio_sds[k]
}

std_X_result   <- standardize_X_cube(X00_cube_train_raw)
X00_cube_train <- std_X_result$X_standardized
x_means        <- std_X_result$means
x_sds          <- std_X_result$sds

X00_cube_test <- X00_cube_test_raw
for(k in std_X_result$standardized_cols){
  X00_cube_test[, k, ] <- (X00_cube_test_raw[, k, ] - x_means[k]) / x_sds[k]
}

## Build A_list and AB_list (CRITICAL: both must have length npt, not npt-1)
# A_list[[t]]:  alive-at-t subject indices (used in Kalman filter)
# AB_list[[t]]: present-at-t subject indices (used in survival likelihood)
A_list_train  <- create_A_list(z_train)
AB_list_train <- create_AB_list(z_train)
A_list_test   <- create_A_list(z_test)
AB_list_test  <- create_AB_list(z_test)

## Dimensions
npt     <- dim(data_split_train)[2]   # 48 months
m_train <- dim(data_split_train)[3]
m_test  <- dim(data_split_test)[3]
p       <- dim(X00_cube_train)[2]     # 6 covariates

cat(sprintf("Train: %d subjects, Test: %d subjects\n", m_train, m_test))
cat(sprintf("Biomarkers: %d, Timepoints: %d, Covariates: %d\n", q, npt, p))

## Verify dimensions before passing to C++
stopifnot(length(A_list_train) == npt)
stopifnot(length(AB_list_train) == npt)

# =============================================================================
# 2. SOURCE LIKELIHOOD FUNCTIONS
# =============================================================================

cat("Sourcing likelihood functions...\n")
source("llh_survival_x_OU.R")          # llh_survival_x_OU: joint llh for cubic-OU
source("filter_estimate_OU_withP.R")   # Kalman filter for OU individual process
source("llh_cs_cs.R")                  # longitudinal llh for cubic-cubic
source("llh_cs_local.R")              # longitudinal llh for cubic-local
source("llh_joint_all_models.R")       # llh_survival_x_cs_cs and llh_survival_x_cs_local
source("helper_functions_losses.R")    # compute_risk_scores_from_filter and loss helpers

# =============================================================================
# 3. FIT MODEL 1: CUBIC-OU
# =============================================================================

cat("\n", paste(rep("=", 60), collapse=""), "\n", sep="")
cat("FITTING MODEL 1: CUBIC-OU\n")

# Construct initial parameter vector (same blending as albumin_fit.R)
load("theta_trans_3_0504.RData"); theta_trans_1 <- theta_trans_3
load("theta_trans_3_0503.RData"); theta_trans_2 <- theta_trans_3
load("theta_trans_3_0502.RData"); theta_trans_4 <- theta_trans_3
rm(theta_trans_3); theta_trans_3 <- theta_trans_1
ind <- 3
theta_trans_3[c(0+ind, 5+ind, 10+ind, 15+ind)] <-
  theta_trans_2[c(0+ind, 5+ind, 10+ind, 15+ind)]
ind <- 5
theta_trans_3[c(0+ind, 5+ind, 10+ind, 15+ind)] <-
  theta_trans_4[c(0+ind, 5+ind, 10+ind, 15+ind)]
load("theta_trans_1_0404.RData")
theta_trans_3[31:42] <- theta_trans_1[31:42]
theta_init_ou <- theta_trans_3

# D_in: maps combined state [alpha_u (2q), alpha_v (q)] to observations
# For OU: alpha_v is q-dimensional (position only)
D_in <- cbind(diag(q) %x% matrix(c(1, 0), nrow = 1, ncol = 2), diag(q))

cat("Optimizing cubic-OU (~3 hours)...\n")
time_ou <- system.time({
  fit_ou <- optim(theta_init_ou, llh_survival_x_OU,
                  data_split_in = data_split_train, z_in = z_train,
                  D_in = D_in, X00_cube_in = X00_cube_train,
                  A_list_in = A_list_train, AB_list_in = AB_list_train,
                  method = "Nelder-Mead", control = list(maxit = 1000))
})

theta_est_ou_trans <- fit_ou$par
theta_est_ou       <- theta_est_ou_trans
theta_est_ou[1:(4*q)] <- exp(theta_est_ou_trans[1:(4*q)])

save(fit_ou, theta_est_ou, theta_est_ou_trans, file = "fit_ou_synth.RData")

# =============================================================================
# 4. FIT MODEL 2: CUBIC-CUBIC
# =============================================================================

cat("\n", paste(rep("=", 60), collapse=""), "\n", sep="")
cat("FITTING MODEL 2: CUBIC-CUBIC\n")

# Parameter structure for cubic-cubic:
# [1:q]      log(zeta): population smoothing variances
# [q+1:2q]   log(lambda): individual cubic spline smoothing variances
# [2q+1:3q]  log(d_vec): Cholesky diagonal of Sigma
# [3q+1:...]  l_vec: Cholesky lower triangle of Sigma
# [n_long]   log(kappa): survival hazard scale
# [+q]       gamma_vec: individual state -> survival (q-dim, position only)
# [+p+1]     gamma_x: survival covariate coefficients

n_long_cc   <- as.integer(0.5*q^2 + 2.5*q + 1)
dim_gamma_cc <- q
n_total_cc  <- n_long_cc + dim_gamma_cc + p + 1

theta_init_cc <- numeric(n_total_cc)
theta_init_cc[1:q]           <- theta_est_ou_trans[1:q]          # zeta from OU
theta_init_cc[(q+1):(2*q)]   <- theta_est_ou_trans[(q+1):(2*q)]  # lambda ~ nu2
theta_init_cc[(2*q+1):(3*q)] <- theta_est_ou_trans[(3*q+1):(4*q)] # d_vec
if(q > 1){
  theta_init_cc[(3*q+1):(as.integer(0.5*q^2 + 2.5*q))] <-
    theta_est_ou_trans[(4*q+1):(as.integer(0.5*q^2 + 3.5*q))]    # l_vec
}
theta_init_cc[n_long_cc] <- log(1.0)   # kappa

# D_in for cubic-cubic: alpha_v is 2q-dimensional (position + slope per biomarker)
D_in_cc <- cbind(diag(q) %x% matrix(c(1, 0), nrow = 1, ncol = 2),
                 diag(q) %x% matrix(c(1, 0), nrow = 1, ncol = 2))

gamma_vec_ou <- theta_est_ou_trans[(as.integer(0.5*q^2 + 3.5*q)+1):(as.integer(0.5*q^2 + 4.5*q))]
gamma_x_ou   <- theta_est_ou_trans[(as.integer(0.5*q^2 + 4.5*q)+1):(as.integer(0.5*q^2 + 4.5*q + p + 1))]
theta_init_cc[(n_long_cc+1):n_total_cc] <- c(gamma_vec_ou, gamma_x_ou)

cat("Optimizing cubic-cubic (~6 hours)...\n")
time_cc <- system.time({
  fit_cc <- optim(theta_init_cc, llh_survival_x_cs_cs,
                  data_split_in = data_split_train, z_in = z_train,
                  D_in = D_in_cc, X00_cube_in = X00_cube_train,
                  A_list_in = A_list_train, AB_list_in = AB_list_train,
                  method = "Nelder-Mead", control = list(maxit = 1000))
})

theta_est_cc_trans <- fit_cc$par
theta_est_cc       <- theta_est_cc_trans
theta_est_cc[1:(3*q)]  <- exp(theta_est_cc_trans[1:(3*q)])
theta_est_cc[n_long_cc] <- exp(theta_est_cc_trans[n_long_cc])

save(fit_cc, theta_est_cc, theta_est_cc_trans, file = "fit_cc_synth.RData")

# =============================================================================
# 5. FIT MODEL 3: CUBIC-LOCAL
# =============================================================================

cat("\n", paste(rep("=", 60), collapse=""), "\n", sep="")
cat("FITTING MODEL 3: CUBIC-LOCAL\n")

# Same parameter structure as cubic-cubic but alpha_v is q-dimensional (local level)
n_long_cl    <- as.integer(0.5*q^2 + 2.5*q + 1)
dim_gamma_cl <- q
n_total_cl   <- n_long_cl + dim_gamma_cl + p + 1

theta_init_cl <- numeric(n_total_cl)
theta_init_cl[1:q]           <- theta_est_ou_trans[1:q]
theta_init_cl[(q+1):(2*q)]   <- theta_est_ou_trans[(q+1):(2*q)] - 2
theta_init_cl[(2*q+1):(3*q)] <- theta_est_ou_trans[(3*q+1):(4*q)]
if(q > 1){
  theta_init_cl[(3*q+1):(as.integer(0.5*q^2 + 2.5*q))] <-
    theta_est_ou_trans[(4*q+1):(as.integer(0.5*q^2 + 3.5*q))]
}
theta_init_cl[n_long_cl] <- log(1.0)

# D_in for cubic-local: alpha_v is q-dimensional (position only, local level)
D_in_cl <- cbind(diag(q) %x% matrix(c(1, 0), nrow = 1, ncol = 2), diag(q))

theta_init_cl[(n_long_cl+1):n_total_cl] <- c(gamma_vec_ou, gamma_x_ou)

cat("Optimizing cubic-local (~3 hours)...\n")
time_cl <- system.time({
  fit_cl <- optim(theta_init_cl, llh_survival_x_cs_local,
                  data_split_in = data_split_train, z_in = z_train,
                  D_in = D_in_cl, X00_cube_in = X00_cube_train,
                  A_list_in = A_list_train, AB_list_in = AB_list_train,
                  method = "Nelder-Mead", control = list(maxit = 1000))
})

theta_est_cl_trans <- fit_cl$par
theta_est_cl       <- theta_est_cl_trans
theta_est_cl[1:(3*q)]  <- exp(theta_est_cl_trans[1:(3*q)])
theta_est_cl[n_long_cl] <- exp(theta_est_cl_trans[n_long_cl])

save(fit_cl, theta_est_cl, theta_est_cl_trans, file = "fit_cl_synth.RData")

# =============================================================================
# 6. TEST-SET LOSS COMPUTATION
# =============================================================================
# Primary metric: negative twice the test-set log-likelihood (-2*loglik).
# Lower = better predictive fit. Used to select individual trajectory model.

cat("\nComputing test-set log-likelihoods...\n")

llh_test_ou <- llh_survival_x_OU(theta_est_ou_trans, data_split_test, z_in = z_test,
                                  D_in = D_in, X00_cube_in = X00_cube_test,
                                  A_list_in = A_list_test, AB_list_in = AB_list_test)

llh_test_cc <- llh_survival_x_cs_cs(theta_est_cc_trans, data_split_test, z_in = z_test,
                                     D_in = D_in_cc, X00_cube_in = X00_cube_test,
                                     A_list_in = A_list_test, AB_list_in = AB_list_test)

llh_test_cl <- llh_survival_x_cs_local(theta_est_cl_trans, data_split_test, z_in = z_test,
                                        D_in = D_in_cl, X00_cube_in = X00_cube_test,
                                        A_list_in = A_list_test, AB_list_in = AB_list_test)

cat(sprintf("Cubic-OU    test -2*loglik: %.2f\n", llh_test_ou))
cat(sprintf("Cubic-Cubic test -2*loglik: %.2f\n", llh_test_cc))
cat(sprintf("Cubic-Local test -2*loglik: %.2f\n", llh_test_cl))

llh_table <- data.frame(
  Model        = c("Cubic-OU", "Cubic-Cubic", "Cubic-Local"),
  Test_neg2llh = c(llh_test_ou, llh_test_cc, llh_test_cl)
)
print(llh_table)

# =============================================================================
# 7. LONGITUDINAL PREDICTION METRICS (MSE / MAE per biomarker)
# =============================================================================

var_names <- c("ALB", "IDWG", "SBP", "NLR", "HGB")

# Run filter on test data using OU fitted parameters (longitudinal subvector only)
theta_long_ou <- theta_est_ou_trans[1:(0.5*q^2 + 3.5*q)]
filter_ou     <- filter_estimate_OU_withP(theta_long_ou, data_split_test, A_list_test)
f_filter_ou   <- filter_ou$f_filter_mat   # q x npt population trajectory
b_filter_ou   <- filter_ou$b_filter_cube  # q x m_test x npt individual deviations

# Build predicted array: f_filter + b_filter gives subject-specific trajectory
y_pred_ou <- array(NA, dim = c(q, npt, m_test))
for(i in 1:m_test){
  y_pred_ou[,,i] <- f_filter_ou + b_filter_ou[, i, ]   # q x npt for subject i
}

# MSE and MAE on standardized scale
mse_by_var_ou <- numeric(q)
mae_by_var_ou <- numeric(q)
for(k in 1:q){
  resid <- y_pred_ou[k,,] - data_split_test[k,,]
  mse_by_var_ou[k] <- mean(resid^2, na.rm = TRUE)
  mae_by_var_ou[k] <- mean(abs(resid), na.rm = TRUE)
}
mse_overall_ou <- mean(mse_by_var_ou)
mae_overall_ou <- mean(mae_by_var_ou)

cat(sprintf("Overall MSE: %.6f, MAE: %.6f\n", mse_overall_ou, mae_overall_ou))
for(k in 1:q){
  cat(sprintf("  %s  MSE: %.6f  MAE: %.6f\n", var_names[k], mse_by_var_ou[k], mae_by_var_ou[k]))
}

# =============================================================================
# 8. SURVIVAL METRICS (AUC and C-index)
# =============================================================================

# Compute individual risk scores: logistic link applied to mean predicted state
# gamma_vec: association between individual biomarker position and log-hazard
# gamma_x: survival covariate coefficients (intercept + p covariates)
risk_scores_ou <- compute_risk_scores_from_filter(
  theta_est_ou_trans, theta_est_ou,
  f_filter_ou, aperm(b_filter_ou, c(1, 3, 2)),   # permute to q x npt x m
  X00_cube_test, D_in, "cubic_ou"
)

# Derive event times and indicators from z_test
# event_times_test: month of death (or npt if censored)
# event_indicator_test: 1 if died, 0 if censored
event_times_test     <- apply(z_test, 1, function(r){ idx <- which(r==1); if(length(idx)>0) min(idx) else npt })
event_indicator_test <- as.numeric(apply(z_test, 1, function(r) any(r==1, na.rm=TRUE)))

# Time-dependent AUC at 6, 12, 24, 36 months
# cases: died by t_eval; controls: still alive at t_eval
eval_times <- c(6, 12, 24, 36)
auc_ou <- sapply(eval_times, function(t_eval){
  cases    <- (event_indicator_test == 1) & (event_times_test <= t_eval)
  controls <- (event_times_test > t_eval)
  usable   <- cases | controls
  if(sum(cases[usable]) > 0 & sum(controls[usable]) > 0){
    roc_obj <- roc(response = cases[usable], predictor = risk_scores_ou[usable],
                   direction = "<", quiet = TRUE)
    return(as.numeric(auc(roc_obj)))
  } else return(NA)
})
names(auc_ou) <- paste0("t", eval_times)

# C-index: concordance between predicted risk and observed survival order
surv_obj   <- Surv(time = event_times_test, event = event_indicator_test)
cindex_ou  <- concordance(surv_obj ~ I(-risk_scores_ou))$concordance

cat(sprintf("\nCubic-OU survival metrics:\n"))
cat(sprintf("  AUC: %s\n", paste(sprintf("t%d=%.3f", eval_times, auc_ou), collapse=", ")))
cat(sprintf("  C-index: %.3f\n", cindex_ou))

# =============================================================================
# 9. SAVE AND PLOT
# =============================================================================

comparison_results <- list(
  llh_table  = llh_table,
  mse_ou     = c(overall = mse_overall_ou, setNames(mse_by_var_ou, var_names)),
  mae_ou     = c(overall = mae_overall_ou, setNames(mae_by_var_ou, var_names)),
  auc_ou     = auc_ou,
  cindex_ou  = cindex_ou,
  fit_times  = c(ou = time_ou[3], cc = time_cc[3], cl = time_cl[3]),
  bio_means  = bio_means,
  bio_sds    = bio_sds
)

save(comparison_results, file = "model_comparison_results.RData")
save.image("master_comparison_synth.RData")

# Plot: -2 log-likelihood comparison
p_llh <- ggplot(llh_table, aes(x = Model, y = Test_neg2llh, fill = Model)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  ylab("-2 * Test Log-Likelihood (lower = better)") +
  ggtitle("Model Comparison: Test-Set Predictive Loss") +
  theme(legend.position = "none")

pdf("model_comparison_plots.pdf", width = 12, height = 5)
print(p_llh)
dev.off()

cat("\n", paste(rep("=", 60), collapse=""), "\n", sep="")
cat(sprintf("Best model (test -2*loglik): %s\n",
            llh_table$Model[which.min(llh_table$Test_neg2llh)]))
cat("Files saved: model_comparison_results.RData, model_comparison_plots.pdf\n")
cat(sprintf("Fit times (min) -- OU: %.1f, CC: %.1f, CL: %.1f\n",
            time_ou[3]/60, time_cc[3]/60, time_cl[3]/60))
